name: CI - Validacion Proyecto

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Ver estructura del proyecto
        run: ls -la

      - name: Validar Docker Compose
        run: docker compose config

      - name: Build de contenedores
        run: docker compose build